
user  nginx;
worker_processes  1;

error_log  /dev/stderr info;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}


http {
    
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format bifrost escape=json
        '{"time":"$time_iso8601",'
        '"request_id":"$request_id",'
        '"client":"$remote_addr",'
        '"method":"$request_method",'
        '"uri":"$request_uri",'
        '"status":$status,'
        '"failure_reason":"$sent_http_x_bifrost_error",'
        '"upstream":"$company_upstream",'
        '"upstream_addr":"$upstream_addr",'
        '"upstream_status":"$upstream_status",'
        '"request_time":"$request_time",'
        '"upstream_connect_time":"$upstream_connect_time",'
        '"upstream_header_time":"$upstream_header_time",'
        '"upstream_response_time":"$upstream_response_time",'
        '"bytes_sent":$body_bytes_sent,'
        '"referer":"$http_referer",'
        '"user_agent":"$http_user_agent",'
        '"forwarded_for":"$http_x_forwarded_for"}';

    access_log /dev/stdout bifrost;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
